### ISSUE TITLE
Errors: test_gpu doesn't work

### ISSUE THREAD

**Issue by oaomly** [baidu-research/warp-ctc#28]
Hi all
I have these errors when I try to run 'test_gpu':

Running GPU tests
terminate called after throwing an instance of 'std::runtime_error'
  what():  Error: compute_ctc_loss in small_test, stat = execution failed
Aborted (core dumped)

Note that: I can run 'test_cpu' without any problems (Running CPU tests, Tests pass)

I was wondering I might miss some libraries or anything else.
Every kind of suggestion would be appreciated!

Thank you so much.

**Comment by bryancatanzaro** [comment]
What kind of GPU do you have?

**Comment by oaomly** [comment]
I have GeForce GTX 580.

**Comment by bryancatanzaro** [comment]
The GTX 580 has compute capability 2.0, but warp-ctc requires compute capability of 3.0 or higher. That's why this error occurs. We don't have plans at the moment to support compute capability 2.0 - it would require some work in the GPU kernels. It's definitely possible, though - feel free to send a pull request.
